const data = {
  qas: [
    {
      question: "What does Recos do?",
      answer:
        "Recos is a web app that transcribes audio content into text using Whisper API. Its advanced editing tools, audio replay functionality, and easy sharing options help to streamline your workflow and boost your productivity.",
    },
    {
      question: "What file formats does Recos support?",
      answer:
        "Recos supports a variety of common audio file formats, including MP3, WAV, M4A, and FLAC. If you encounter any issues with a specific file format, please contact our customer support team for assistance.",
    },
    {
      question: "How accurate is Recos' transcription?",
      answer:
        "Recos is designed to provide fast and accurate transcription results. While its accuracy may vary depending on factors such as audio quality and speaker accents, users can typically expect around 95% accuracy or higher.",
    },
    {
      question: "Can I edit my transcriptions in Recos?",
      answer:
        "Yes! Recos includes advanced editing tools that allow you to polish your transcription text, as well as a feature that enables you to listen to the audio as you edit.",
    },
    {
      question: "What sharing options does Recos offer?",
      answer:
        "Recos makes it easy to share your transcriptions via email, download them as a text file, or send them directly to your favorite cloud storage service. You can also share a link to your transcription on social media or embed it directly on your website.",
    },
  ],
};
const WhatIsRecos = () => {
  return (
    <div className="mt-64">
      <div className="border-t-2 border-green-500 py-2"></div>
      {data.qas.map((item) => (
        <div key={item.question}>
          <div className="my-4 text-xl font-bold dark:text-white">
            {item.question}
          </div>
          <div className="text-lg dark:text-white">{item.answer}</div>
        </div>
      ))}
      <div className="mt-3 text-red-600">
        Warning! The above content is generated by ChatGPT, you should ignore it
        :)
      </div>
      <div className="border-b-2 border-green-500 py-4"></div>
    </div>
  );
};

export default WhatIsRecos;
